import { MySQL, SQLDialect, SQLDialectSpec } from '@codemirror/lang-sql';

// Trino & Hive & StarRocks ship no dialect with @codemirror/lang-sql. We define
// our own here using the reserved-word + builtin-function tables from each
// engine's documentation. The lists below are the subsets that meaningfully
// disambiguate the dialect from one another — exhaustive coverage matters
// less than getting the engine-specific names right (UNNEST, LATERAL VIEW,
// BITMAP_UNION, etc.) so completions feel native.

const SHARED_TYPES =
  'BIGINT INTEGER INT SMALLINT TINYINT DOUBLE FLOAT REAL DECIMAL NUMERIC ' +
  'VARCHAR CHAR STRING TEXT BOOLEAN BOOL DATE TIME TIMESTAMP INTERVAL ' +
  'ARRAY MAP STRUCT ROW JSON BINARY VARBINARY UUID';

// Trino reserved keywords from
// https://trino.io/docs/current/language/reserved.html
const TRINO_KEYWORDS =
  'ABSENT ADD ALL ALTER AND ANY ARRAY AS ASC AT AUTHORIZATION BERNOULLI ' +
  'BETWEEN BOTH BY CALL CASCADE CASE CAST CATALOG CATALOGS CONDITIONAL ' +
  'CONFIGURATION CONSTRAINT COMMIT COMMENT COMMITTED COMPUTE COPARTITION ' +
  'CREATE CROSS CUBE CURRENT CURRENT_CATALOG CURRENT_DATE CURRENT_PATH ' +
  'CURRENT_ROLE CURRENT_SCHEMA CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER ' +
  'DEALLOCATE DECLARE DEFAULT DEFERRABLE DEFINE DELETE DENY DESC DESCRIBE ' +
  'DESCRIPTOR DETERMINISTIC DISTINCT DISTRIBUTED DROP ELSE EMPTY ENCODING ' +
  'END ERROR ESCAPE EXCEPT EXCLUDING EXECUTE EXISTS EXPLAIN EXTRACT FALSE ' +
  'FETCH FILTER FINAL FIRST FOLLOWING FOR FORMAT FROM FULL FUNCTION ' +
  'FUNCTIONS GRANT GRANTED GRANTS GRAPHVIZ GROUP GROUPING GROUPS HAVING ' +
  'IF IGNORE IMMEDIATE IN INCLUDING INITIAL INNER INPUT INSERT INTERSECT ' +
  'INTERVAL INTO INVOKER IS IS_PRINCIPAL JOIN JSON_ARRAY JSON_EXISTS ' +
  'JSON_OBJECT JSON_QUERY JSON_TABLE JSON_VALUE KEEP KEY KEYS LANGUAGE ' +
  'LAST LATERAL LEADING LEFT LEVEL LIKE LIMIT LISTAGG LOCAL LOCALTIME ' +
  'LOCALTIMESTAMP LOGICAL MAP MATCH MATCHED MATCHES MATCH_RECOGNIZE ' +
  'MATERIALIZED MEASURES MERGE NATURAL NESTED NEXT NFC NFD NFKC NFKD NO ' +
  'NONE NORMALIZE NOT NULL NULLIF NULLS OBJECT OF OFFSET OMIT ON ONE ONLY ' +
  'OPTION OR ORDER ORDINALITY OUTER OUTPUT OVER OVERFLOW PARTITION ' +
  'PARTITIONS PASSING PAST PATH PATTERN PER PERMUTE POSITION PRECEDING ' +
  'PRECISION PREPARE PRIMARY PROPERTIES PRUNE QUOTES RANGE READ RECURSIVE ' +
  'REFRESH RENAME REPEATABLE REPLACE RESET RESPECT RESTRICT RETURN ' +
  'RETURNING RETURNS REVOKE RIGHT ROLE ROLES ROLLBACK ROLLUP ROW ROWS ' +
  'RUNNING SCALAR SCHEMA SCHEMAS SECURITY SEEK SELECT SERIALIZABLE SESSION ' +
  'SET SETS SHOW SKIP SOME START STATS SUBSET SUBSTRING SYSTEM TABLE ' +
  'TABLES TABLESAMPLE TEXT THEN TIES TIME TIMESTAMP TO TRAILING TRANSACTION ' +
  'TRIM TRUE TRUNCATE TRY_CAST TYPE UESCAPE UNBOUNDED UNCOMMITTED UNCONDITIONAL ' +
  'UNION UNIQUE UNKNOWN UNMATCHED UNNEST UNTIL UPDATE USE USER USING UTF16 ' +
  'UTF32 UTF8 VALIDATE VALUE VALUES VERBOSE VERSION VIEW WHEN WHERE WHILE ' +
  'WINDOW WITH WITHIN WITHOUT WORK WRAPPER WRITE YEAR ZONE';

// Trino common functions — abridged from
// https://trino.io/docs/current/functions.html (the most-used set).
const TRINO_BUILTINS =
  'ABS ARBITRARY ARRAY_AGG ARRAY_DISTINCT ARRAY_INTERSECT ARRAY_JOIN ' +
  'ARRAY_MAX ARRAY_MIN ARRAY_POSITION ARRAY_REMOVE ARRAY_SORT ARRAY_UNION ' +
  'APPROX_DISTINCT APPROX_PERCENTILE AVG BIT_COUNT BOOL_AND BOOL_OR CARDINALITY ' +
  'CBRT CEIL CEILING CHAR_LENGTH CHR COALESCE CONCAT CONTAINS CORR ' +
  'COSINE_SIMILARITY COUNT COUNT_IF COVAR_POP COVAR_SAMP CUME_DIST ' +
  'CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP DATE DATE_ADD DATE_DIFF ' +
  'DATE_FORMAT DATE_PARSE DATE_TRUNC DAY DAY_OF_MONTH DAY_OF_WEEK DAY_OF_YEAR ' +
  'DECODE DEGREES DENSE_RANK ELEMENT_AT EVERY EXP FILTER FIRST_VALUE ' +
  'FLATTEN FLOOR FORMAT FORMAT_DATETIME FROM_BASE FROM_UNIXTIME GEOMETRIC_MEAN ' +
  'GREATEST HISTOGRAM HOUR HMAC_MD5 HMAC_SHA1 HMAC_SHA256 IF INFINITY ' +
  'IS_FINITE IS_INFINITE IS_NAN JSON_ARRAY_CONTAINS JSON_EXTRACT ' +
  'JSON_EXTRACT_SCALAR JSON_FORMAT JSON_PARSE JSON_SIZE LAG LAST_DAY_OF_MONTH ' +
  'LAST_VALUE LEAD LEAST LENGTH LEVENSHTEIN_DISTANCE LIKE LISTAGG LN LOG2 ' +
  'LOG10 LOWER LPAD LTRIM MAP MAP_AGG MAP_CONCAT MAP_FILTER MAP_KEYS MAP_VALUES ' +
  'MAP_ZIP_WITH MAX MAX_BY MD5 MILLISECOND MIN MIN_BY MINUTE MOD MONTH ' +
  'MULTIMAP_AGG NAN NORMALIZE NOW NTH_VALUE NULLIF NUMERIC_HISTOGRAM PERCENT_RANK ' +
  'PI POSITION POW POWER QUARTER RADIANS RAND RANDOM RANK REDUCE REGEXP_EXTRACT ' +
  'REGEXP_EXTRACT_ALL REGEXP_LIKE REGEXP_REPLACE REGEXP_SPLIT REPEAT REPLACE ' +
  'REVERSE ROUND ROW_NUMBER RPAD RTRIM SECOND SEQUENCE SHA1 SHA256 SHA512 SIGN ' +
  'SIN SLICE SPLIT SPLIT_PART SQRT STDDEV STDDEV_POP STDDEV_SAMP STRPOS SUBSTR ' +
  'SUBSTRING SUM TANH TIMESTAMP TO_BASE TO_BASE64 TO_HEX TO_ISO8601 TO_UNIXTIME ' +
  'TO_UTF8 TRANSFORM TRANSFORM_KEYS TRANSFORM_VALUES TRIM TRY TRY_CAST TYPEOF ' +
  'UNNEST UPPER URL_DECODE URL_ENCODE URL_EXTRACT_HOST URL_EXTRACT_PATH ' +
  'URL_EXTRACT_PROTOCOL UUID VAR_POP VAR_SAMP VARIANCE WEEK WIDTH_BUCKET WORD_STEM ' +
  'XXHASH64 YEAR ZIP ZIP_WITH';

// Hive: HiveQL reserved + non-reserved keywords (Hive 3 LanguageManual).
const HIVE_KEYWORDS =
  'ADD ADMIN AFTER ALL ALTER ANALYZE AND ARCHIVE ARRAY AS ASC AT AUTHORIZATION ' +
  'BEFORE BETWEEN BIGINT BINARY BOOLEAN BOTH BUCKET BUCKETS BY CASCADE CASE CAST ' +
  'CHANGE CHAR CLUSTER CLUSTERED CLUSTERSTATUS COLLECTION COLUMN COLUMNS COMMENT ' +
  'COMPACT COMPACTIONS COMPUTE CONCATENATE CONF CONSTRAINT CONTINUE CREATE CROSS ' +
  'CUBE CURRENT CURRENT_DATE CURRENT_TIMESTAMP CURSOR DATA DATABASE DATABASES DATE ' +
  'DATETIME DAY DBPROPERTIES DECIMAL DEFAULT DEFERRED DEFINED DELETE DELIMITED ' +
  'DEPENDENCY DESC DESCRIBE DIRECTORIES DIRECTORY DISABLE DISTINCT DISTRIBUTE ' +
  'DOUBLE DROP ELEM_TYPE ELSE ENABLE END ESCAPED EXCHANGE EXCLUSIVE EXISTS ' +
  'EXPLAIN EXPORT EXTENDED EXTERNAL EXTRACT FALSE FETCH FIELDS FILE FILEFORMAT ' +
  'FIRST FLOAT FLOOR FOLLOWING FOR FORMAT FORMATTED FROM FULL FUNCTION FUNCTIONS ' +
  'GRANT GROUP GROUPING HAVING HOLD_DDLTIME HOUR IDXPROPERTIES IF IGNORE IMPORT IN ' +
  'INDEX INDEXES INNER INPATH INPUTDRIVER INPUTFORMAT INSERT INT INTEGER INTERSECT ' +
  'INTERVAL INTO IS ITEMS JOIN JAR KEY KEYS KEY_TYPE LATERAL LEFT LESS LIKE LIMIT ' +
  'LINES LOAD LOCAL LOCATION LOCK LOCKS LOGICAL LONG MACRO MAP MAPJOIN MATERIALIZED ' +
  'METADATA MINUS MINUTE MONTH MORE MSCK NONE NOSCAN NOT NO_DROP NULL NULLS OF ' +
  'OFFLINE OFFSET ON ONLY OPTION OR ORDER OUT OUTER OUTPUTDRIVER OUTPUTFORMAT OVER ' +
  'OVERWRITE OWNER PARTIALSCAN PARTITION PARTITIONED PARTITIONS PERCENT PLUS ' +
  'PRECEDING PRECISION PRESERVE PRETTY PRIMARY PRINCIPALS PROCEDURE PROTECTION ' +
  'PURGE QUARTER QUERY RANGE READ READONLY READS REBUILD RECORDREADER RECORDWRITER ' +
  'REDUCE REFERENCES REGEXP RELOAD RENAME REPAIR REPLACE REPLICATION RESTRICT ' +
  'REVOKE REWRITE RIGHT RLIKE ROLE ROLES ROLLBACK ROLLUP ROW ROWS SCHEMA SCHEMAS ' +
  'SECOND SELECT SEMI SERDE SERDEPROPERTIES SERVER SET SETS SHARED SHOW ' +
  'SHOW_DATABASE SKEWED SMALLINT SNAPSHOT SORT SORTED SSL STATISTICS STORED ' +
  'STREAMTABLE STRING STRUCT SYNC TABLE TABLES TABLESAMPLE TBLPROPERTIES TEMPORARY ' +
  'TERMINATED THEN TIMESTAMP TINYINT TO TOUCH TRANSACTION TRANSACTIONS TRANSFORM ' +
  'TRIGGER TRUE TRUNCATE UNARCHIVE UNBOUNDED UNDO UNION UNIONTYPE UNIQUEJOIN UNLOCK ' +
  'UNSET UNSIGNED UPDATE USE USER USING UTC UTC_TIMESTAMP VALUES VALUE_TYPE VARCHAR ' +
  'VIEW VIEWS WAIT WEEK WHEN WHERE WHILE WINDOW WITH WORK WRITE YEAR ZONE';

const HIVE_BUTLINS_PREFIX =
  'ABS ACOS ARRAY ARRAY_CONTAINS ASCII ASIN ASSERT_TRUE ATAN AVG BASE64 ' +
  'BIN BINARY BLOOM_FILTER CAST CBRT CEIL CEILING CHAR_LENGTH CHR COALESCE ' +
  'COLLECT_LIST COLLECT_SET COMPUTE_STATS CONCAT CONCAT_WS CONTEXT_NGRAMS ' +
  'CORR COS COUNT COVAR_POP COVAR_SAMP CRC32 CUME_DIST CURRENT_DATABASE ' +
  'CURRENT_DATE CURRENT_TIMESTAMP CURRENT_USER DATE_ADD DATE_DIFF DATE_FORMAT ' +
  'DATE_SUB DATEDIFF DAY DAYOFMONTH DAYOFWEEK DECODE DEGREES DENSE_RANK ' +
  'ELT ENCODE EWAH_BITMAP EXP EXPLODE FACTORIAL FIND_IN_SET FIRST_VALUE FLOOR ' +
  'FORMAT_NUMBER FROM_UNIXTIME FROM_UTC_TIMESTAMP GET_JSON_OBJECT GREATEST ' +
  'GROUPING HASH HEX HISTOGRAM_NUMERIC HOUR IF IN_FILE INDEX INITCAP INLINE ' +
  'INSTR IS_NULL ISNOTNULL JAVA_METHOD JSON_TUPLE LAG LAST_DAY LAST_VALUE LCASE ' +
  'LEAD LEAST LENGTH LEVENSHTEIN LIKE LN LOCATE LOG LOG10 LOG2 LOWER LPAD LTRIM ' +
  'MAP MAP_KEYS MAP_VALUES MASK MAX MIN MINUTE MONTH MONTHS_BETWEEN NAMED_STRUCT ' +
  'NEGATIVE NEXT_DAY NGRAMS NTILE NVL PARSE_URL PARSE_URL_TUPLE PERCENT_RANK ' +
  'PERCENTILE PERCENTILE_APPROX PI PMOD POSEXPLODE POSITIVE POW POWER PRINTF ' +
  'QUARTER RADIANS RAND RANK REFLECT REGEXP_EXTRACT REGEXP_REPLACE REPEAT ' +
  'REVERSE ROUND ROW_NUMBER RPAD RTRIM SECOND SENTENCES SHA SHA1 SHA2 SHIFTLEFT ' +
  'SHIFTRIGHT SIGN SIN SIZE SOUNDEX SPACE SPLIT SQRT STACK STD STDDEV STDDEV_POP ' +
  'STDDEV_SAMP STR_TO_MAP STRUCT SUBSTR SUBSTRING SUBSTRING_INDEX SUM TAN ' +
  'TO_DATE TO_UNIX_TIMESTAMP TO_UTC_TIMESTAMP TRANSLATE TRIM TRUNC TYPEOF UCASE ' +
  'UNBASE64 UNHEX UNIX_TIMESTAMP UPPER UUID VAR_POP VAR_SAMP VARIANCE VERSION ' +
  'WEEKOFYEAR WIDTH_BUCKET WINDOWING_TABLE_FUNCTION XPATH YEAR';

// StarRocks: MySQL-compatible base + StarRocks-specific functions
// (https://docs.starrocks.io/docs/sql-reference/sql-functions/).
const STARROCKS_EXTRA_KEYWORDS =
  'AGGREGATE ARRAY BACKUP BITMAP BROKER CATALOGS CHARSET CLUSTER COLLATE COMPUTE ' +
  'CONFIG CURRENT_GROUP CURRENT_GROUPS DECOMMISSION DUPLICATE DYNAMIC ENGINE ' +
  'EVENTS EXTERNAL FE FILE FRONTEND FROM_BASE FUNCTIONS HISTOGRAM HLL ' +
  'HOSTNAME LABEL MATERIALIZED METADATA NAMES NETWORK OBSERVER OFFSET ONLY ' +
  'OPTIMIZE OUTFILE PARTITIONS PERCENTILE PIPE PIPES PLUGIN PLUGINS POLICIES ' +
  'POLICY PRIMARY PROC PROPERTIES PROPERTY QUERY QUEUE RECOVER REFRESH ' +
  'REPOSITORIES REPOSITORY RESOURCE RESOURCES RESTORE RESUME ROLLUP ROUTINE RULE ' +
  'RUNTIMEFILTER SCHEMAS SHRINK STATS STORAGE STREAM SUSPEND TABLET TABLETS ' +
  'TEMPORARY USAGE WAREHOUSE WAREHOUSES WORKLOAD';

const STARROCKS_EXTRA_BUILTINS =
  'ARRAY_AGG ARRAY_AVG ARRAY_CONCAT ARRAY_CONTAINS ARRAY_DIFFERENCE ARRAY_DISTINCT ' +
  'ARRAY_FILTER ARRAY_INTERSECT ARRAY_JOIN ARRAY_LENGTH ARRAY_MAX ARRAY_MIN ' +
  'ARRAY_POSITION ARRAY_REMOVE ARRAY_SLICE ARRAY_SORT ARRAY_SUM ARRAYS_OVERLAP ' +
  'BITMAP_AND BITMAP_AND_COUNT BITMAP_CONTAINS BITMAP_COUNT BITMAP_EMPTY ' +
  'BITMAP_FROM_STRING BITMAP_HASH BITMAP_INTERSECT BITMAP_OR BITMAP_OR_COUNT ' +
  'BITMAP_TO_STRING BITMAP_UNION BITMAP_UNION_COUNT BITMAP_XOR ' +
  'COALESCE CONCAT CONCAT_WS COUNT_DISTINCT CURRENT_VERSION ' +
  'DATE_DIFF DATE_FORMAT DATE_SLICE DATE_SUB DATE_TRUNC DAYS_DIFF ' +
  'GET_JSON_DOUBLE GET_JSON_INT GET_JSON_STRING ' +
  'HLL_CARDINALITY HLL_EMPTY HLL_HASH HLL_UNION HLL_UNION_AGG ' +
  'INSTR JSON_ARRAY JSON_EXISTS JSON_LENGTH JSON_OBJECT JSON_QUERY JSON_STRING ' +
  'JSON_TYPE LAG LEAD ' +
  'MAP_KEYS MAP_SIZE MAP_VALUES MAX_BY MIN_BY MULTI_DISTINCT_COUNT MULTI_DISTINCT_SUM ' +
  'NDV NULLIF NVL ' +
  'PERCENTILE_APPROX PERCENTILE_CONT PERCENTILE_DISC PERCENTILE_UNION ' +
  'REGEXP_EXTRACT REGEXP_REPLACE REPEAT REPLACE REVERSE ROUND ROW_NUMBER ' +
  'SPLIT SPLIT_PART SQRT STDDEV STDDEV_POP STDDEV_SAMP STR_TO_DATE STR_TO_MAP ' +
  'TIME_SLICE TIMESTAMP TO_BITMAP TO_DATE TO_DAYS TO_JSON TO_UNIX_TIMESTAMP ' +
  'UNIX_TIMESTAMP UPPER WEEK_OF_YEAR WINDOW_FUNNEL YEARS_DIFF';

const MYSQL_KEYWORDS_FOR_STARROCKS =
  'ADD ALL ALTER ANALYZE AND AS ASC ASENSITIVE BEFORE BETWEEN BIGINT BINARY ' +
  'BIT BLOB BOTH BY CALL CASCADE CASE CAST CHANGE CHAR CHARACTER CHECK COLLATE ' +
  'COLUMN COMMIT CONDITION CONNECTION CONSTRAINT CONTINUE CONVERT CREATE CROSS ' +
  'CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE ' +
  'DATABASES DATE DAY_HOUR DAY_MICROSECOND DAY_MINUTE DAY_SECOND DEC DECIMAL ' +
  'DECLARE DEFAULT DELAYED DELETE DESC DESCRIBE DETERMINISTIC DISTINCT ' +
  'DISTINCTROW DIV DOUBLE DROP DUAL EACH ELSE ELSEIF ENCLOSED ESCAPED EXISTS ' +
  'EXIT EXPLAIN FALSE FETCH FLOAT FOR FORCE FOREIGN FROM FULLTEXT GRANT GROUP ' +
  'HAVING HIGH_PRIORITY HOUR_MICROSECOND HOUR_MINUTE HOUR_SECOND IF IGNORE IN ' +
  'INDEX INFILE INNER INOUT INSENSITIVE INSERT INT INTEGER INTERVAL INTO IS ' +
  'ITERATE JOIN KEY KEYS KILL LEADING LEAVE LEFT LIKE LIMIT LINEAR LINES LOAD ' +
  'LOCALTIME LOCALTIMESTAMP LOCK LONG LONGBLOB LONGTEXT LOOP LOW_PRIORITY ' +
  'MATCH MEDIUMBLOB MEDIUMINT MEDIUMTEXT MINUTE_MICROSECOND MINUTE_SECOND MOD ' +
  'MODIFIES NATURAL NOT NULL NUMERIC ON OPTIMIZE OPTION OR ORDER OUT OUTER ' +
  'OUTFILE PRECISION PRIMARY PROCEDURE PURGE READ READS REAL REFERENCES REGEXP ' +
  'RELEASE RENAME REPEAT REPLACE REQUIRE RESIGNAL RESTRICT RETURN REVOKE RIGHT ' +
  'RLIKE SCHEMA SCHEMAS SECOND_MICROSECOND SELECT SENSITIVE SEPARATOR SET SHOW ' +
  'SIGNAL SMALLINT SPATIAL SPECIFIC SQL SQLEXCEPTION SQLSTATE SQLWARNING SSL ' +
  'STARTING STRAIGHT_JOIN TABLE TERMINATED THEN TINYBLOB TINYINT TINYTEXT TO ' +
  'TRAILING TRIGGER TRUE UNDO UNION UNIQUE UNLOCK UNSIGNED UPDATE USAGE USE ' +
  'USING UTC_DATE UTC_TIME UTC_TIMESTAMP VALUES VARBINARY VARCHAR VARCHARACTER ' +
  'VARYING VIEW WHEN WHERE WHILE WITH WRITE XOR YEAR_MONTH ZEROFILL';

const TRINO_SPEC: SQLDialectSpec = {
  keywords: TRINO_KEYWORDS.toLowerCase(),
  builtin: TRINO_BUILTINS.toLowerCase(),
  types: SHARED_TYPES.toLowerCase(),
  doubleQuotedStrings: false,
  backslashEscapes: false,
  hashComments: false,
  operatorChars: '*+-%<>!=&|^/'
};

const HIVE_SPEC: SQLDialectSpec = {
  keywords: HIVE_KEYWORDS.toLowerCase(),
  builtin: HIVE_BUTLINS_PREFIX.toLowerCase(),
  types: SHARED_TYPES.toLowerCase(),
  doubleQuotedStrings: true,
  backslashEscapes: true,
  hashComments: false,
  slashComments: false
};

const STARROCKS_SPEC: SQLDialectSpec = {
  keywords: (
    MYSQL_KEYWORDS_FOR_STARROCKS +
    ' ' +
    STARROCKS_EXTRA_KEYWORDS
  ).toLowerCase(),
  builtin: STARROCKS_EXTRA_BUILTINS.toLowerCase(),
  types: SHARED_TYPES.toLowerCase(),
  doubleQuotedStrings: false,
  backslashEscapes: true,
  hashComments: true,
  operatorChars: '*+-%<>!=&|^'
};

export const Trino: SQLDialect = SQLDialect.define(TRINO_SPEC);
export const Hive: SQLDialect = SQLDialect.define(HIVE_SPEC);
// Inherit MySQL's lexer behavior + add StarRocks-specific keywords/functions.
// `SQLDialect.define` won't merge from MySQL automatically, so we ship the
// merged keyword set above. We still keep `MySQL` available as a fallback
// for users who prefer strict MySQL completions.
export const StarRocks: SQLDialect = SQLDialect.define(STARROCKS_SPEC);
export { MySQL };
